export let countryArr = [
  {
    userId: 1,
    id: 1,
    title: 'India',
    body: 'India is a diverse country known for its rich culture, history, and traditions. It is home to ancient civilizations, vibrant festivals, and a rapidly growing economy.',
  },
  {
    userId: 1,
    id: 2,
    title: 'United States',
    body: 'The United States is known for its technological innovation and cultural influence. It has a diverse population and a strong global presence.',
  },
  {
    userId: 1,
    id: 3,
    title: 'United Kingdom',
    body: 'The United Kingdom is famous for its historic landmarks, monarchy, and cultural heritage. It has played a major role in world history.',
  },
  {
    userId: 1,
    id: 4,
    title: 'Canada',
    body: 'Canada is known for its natural beauty, multicultural society, and high quality of life. It offers vast landscapes and peaceful living.',
  },
  {
    userId: 1,
    id: 5,
    title: 'Australia',
    body: 'Australia is famous for its unique wildlife, beaches, and outdoor lifestyle. It is a popular destination for tourism and education.',
  },
  {
    userId: 1,
    id: 6,
    title: 'Germany',
    body: 'Germany is known for its engineering excellence, strong economy, and rich cultural history. It is a leader in technology and manufacturing.',
  },
  {
    userId: 1,
    id: 7,
    title: 'France',
    body: 'France is renowned for its art, fashion, cuisine, and iconic landmarks. It is one of the most visited countries in the world.',
  },
  {
    userId: 1,
    id: 8,
    title: 'Japan',
    body: 'Japan blends ancient traditions with modern technology. It is famous for innovation, discipline, and cultural richness.',
  },
  {
    userId: 1,
    id: 9,
    title: 'China',
    body: 'China has one of the world’s oldest civilizations and a rapidly growing economy. It is known for its manufacturing and technological progress.',
  },
  {
    userId: 1,
    id: 10,
    title: 'Brazil',
    body: 'Brazil is known for its vibrant culture, football passion, and Amazon rainforest. It is the largest country in South America.',
  },
  {
    userId: 1,
    id: 11,
    title: 'Russia',
    body: 'Russia is the largest country in the world by area. It has a rich literary history and vast natural resources.',
  },
  {
    userId: 1,
    id: 12,
    title: 'Italy',
    body: 'Italy is famous for its ancient history, art, architecture, and cuisine. It is the birthplace of the Roman Empire and Renaissance.',
  },
  {
    userId: 1,
    id: 13,
    title: 'Spain',
    body: 'Spain is known for its lively festivals, rich history, and Mediterranean lifestyle. It has a strong cultural heritage.',
  },
  {
    userId: 1,
    id: 14,
    title: 'South Africa',
    body: 'South Africa is known for its natural diversity, wildlife, and cultural mix. It is often called the Rainbow Nation.',
  },
  {
    userId: 1,
    id: 15,
    title: 'New Zealand',
    body: 'New Zealand is famous for its scenic landscapes, adventure sports, and peaceful environment.',
  },
  {
    userId: 1,
    id: 16,
    title: 'Mexico',
    body: 'Mexico is rich in history and traditions, known for its cuisine, festivals, and ancient civilizations.',
  },
  {
    userId: 1,
    id: 17,
    title: 'Egypt',
    body: 'Egypt is home to one of the world’s oldest civilizations. It is famous for pyramids, pharaohs, and ancient monuments.',
  },
  {
    userId: 1,
    id: 18,
    title: 'United Arab Emirates',
    body: 'The UAE is known for modern cities, luxury lifestyle, and rapid development. Dubai is a major global hub.',
  },
  {
    userId: 1,
    id: 19,
    title: 'Singapore',
    body: 'Singapore is a global financial center known for cleanliness, safety, and efficient infrastructure.',
  },
  {
    userId: 1,
    id: 20,
    title: 'Switzerland',
    body: 'Switzerland is famous for its neutrality, banking system, and beautiful Alpine landscapes.',
  },
];
