export const movieData = [
  {
    userId: 1,
    id: 1,
    title: 'The Shawshank Redemption',
    body: 'Two imprisoned men bond over years, finding solace and redemption through acts of common decency.',
  },
  {
    userId: 1,
    id: 2,
    title: 'The Godfather',
    body: 'The aging patriarch of an organized crime dynasty transfers control of his empire to his reluctant son.',
  },
  {
    userId: 1,
    id: 3,
    title: 'The Dark Knight',
    body: 'Batman faces the Joker, a criminal mastermind who plunges Gotham into chaos and tests his morals.',
  },
  {
    userId: 1,
    id: 4,
    title: 'Inception',
    body: 'A thief who steals corporate secrets through dream-sharing technology is given a chance at redemption.',
  },
  {
    userId: 1,
    id: 5,
    title: 'Fight Club',
    body: 'An office worker and a soap maker form an underground fight club that evolves into something dangerous.',
  },
  {
    userId: 1,
    id: 6,
    title: 'Forrest Gump',
    body: 'The life journey of a simple man whose kindness and optimism shape extraordinary events.',
  },
  {
    userId: 1,
    id: 7,
    title: 'Interstellar',
    body: 'A team of explorers travel through a wormhole in space to ensure humanity’s survival.',
  },
  {
    userId: 1,
    id: 8,
    title: 'Gladiator',
    body: 'A former Roman general seeks revenge against the corrupt emperor who murdered his family.',
  },
  {
    userId: 1,
    id: 9,
    title: 'Titanic',
    body: 'A love story unfolds aboard the ill-fated Titanic during its tragic maiden voyage.',
  },
  {
    userId: 1,
    id: 10,
    title: 'The Matrix',
    body: 'A hacker learns the reality he lives in is a simulation and joins a rebellion against machines.',
  },
  {
    userId: 1,
    id: 11,
    title: 'Avengers: Endgame',
    body: 'The Avengers assemble one final time to undo the devastation caused by Thanos.',
  },
  {
    userId: 1,
    id: 12,
    title: 'Jurassic Park',
    body: 'Scientists clone dinosaurs for a theme park, but chaos erupts when the creatures escape.',
  },
  {
    userId: 1,
    id: 13,
    title: 'The Lion King',
    body: 'A young lion prince flees his kingdom after tragedy, only to learn his true destiny.',
  },
  {
    userId: 1,
    id: 14,
    title: 'Pulp Fiction',
    body: 'Interconnected stories of crime unfold in a nonlinear narrative filled with dark humor.',
  },
  {
    userId: 1,
    id: 15,
    title: 'Parasite',
    body: 'A poor family schemes to become employed by a wealthy household with unforeseen consequences.',
  },
  {
    userId: 1,
    id: 16,
    title: 'Joker',
    body: 'A troubled comedian descends into madness and becomes a symbol of chaos in Gotham.',
  },
  {
    userId: 1,
    id: 17,
    title: 'The Lord of the Rings: Fellowship of the Ring',
    body: 'A hobbit begins a perilous journey to destroy a powerful ring and save Middle-earth.',
  },
  {
    userId: 1,
    id: 18,
    title: 'Star Wars: A New Hope',
    body: 'A young farm boy joins a rebellion to defeat a tyrannical galactic empire.',
  },
  {
    userId: 1,
    id: 19,
    title: 'Harry Potter and the Sorcerer’s Stone',
    body: 'A young boy discovers he is a wizard and begins his journey at a magical school.',
  },
  {
    userId: 1,
    id: 20,
    title: 'Avatar',
    body: 'A marine on an alien planet becomes torn between following orders and protecting a new world.',
  },
];
