export let vehicalData = [
  {
    userId: 1,
    id: 1,
    title: 'Tesla Model S',
    body: 'A premium electric sedan known for its long range, high performance, and advanced autopilot features.',
  },
  {
    userId: 1,
    id: 2,
    title: 'Toyota Corolla',
    body: 'A reliable and fuel-efficient sedan popular for daily commuting and low maintenance costs.',
  },
  {
    userId: 1,
    id: 3,
    title: 'Honda Civic',
    body: 'A sporty and efficient car offering comfort, modern technology, and strong resale value.',
  },
  {
    userId: 1,
    id: 4,
    title: 'Ford Mustang',
    body: 'An iconic American muscle car famous for its powerful engine and aggressive design.',
  },
  {
    userId: 1,
    id: 5,
    title: 'BMW 3 Series',
    body: 'A luxury sedan combining performance, comfort, and advanced driving technology.',
  },
  {
    userId: 1,
    id: 6,
    title: 'Audi A4',
    body: 'A stylish luxury car with a refined interior and smooth driving experience.',
  },
  {
    userId: 1,
    id: 7,
    title: 'Mercedes-Benz C-Class',
    body: 'A premium sedan offering elegance, safety, and cutting-edge features.',
  },
  {
    userId: 1,
    id: 8,
    title: 'Hyundai Creta',
    body: 'A popular compact SUV with modern design, comfort, and advanced features.',
  },
  {
    userId: 1,
    id: 9,
    title: 'Kia Seltos',
    body: 'A stylish SUV offering strong performance, safety features, and a bold look.',
  },
  {
    userId: 1,
    id: 10,
    title: 'Mahindra Thar',
    body: 'A rugged off-road SUV designed for adventure and challenging terrains.',
  },
  {
    userId: 1,
    id: 11,
    title: 'Royal Enfield Classic 350',
    body: 'A timeless motorcycle known for its retro design and powerful cruising performance.',
  },
  {
    userId: 1,
    id: 12,
    title: 'KTM Duke 390',
    body: 'A high-performance street motorcycle with aggressive styling and advanced features.',
  },
  {
    userId: 1,
    id: 13,
    title: 'Yamaha R15',
    body: 'A sporty bike offering sharp handling, aerodynamic design, and racing-inspired performance.',
  },
  {
    userId: 1,
    id: 14,
    title: 'Honda Activa',
    body: 'A reliable and fuel-efficient scooter ideal for daily city commuting.',
  },
  {
    userId: 1,
    id: 15,
    title: 'TVS Apache RTR 160',
    body: 'A performance-oriented motorcycle with sporty design and responsive handling.',
  },
  {
    userId: 1,
    id: 16,
    title: 'Tata Nexon EV',
    body: 'An electric SUV offering safety, modern features, and eco-friendly driving.',
  },
  {
    userId: 1,
    id: 17,
    title: 'Maruti Suzuki Swift',
    body: 'A compact hatchback known for its peppy performance and fuel efficiency.',
  },
  {
    userId: 1,
    id: 18,
    title: 'Volkswagen Polo',
    body: 'A solidly built hatchback offering excellent driving dynamics and safety.',
  },
  {
    userId: 1,
    id: 19,
    title: 'Jeep Compass',
    body: 'A premium SUV with strong off-road capability and refined interior.',
  },
  {
    userId: 1,
    id: 20,
    title: 'Suzuki Access 125',
    body: 'A comfortable scooter offering smooth performance and practical features.',
  },
];
